repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    values:
      - crds:
          enabled: true
          keep: false
    labels:
      base: true
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.15.7
    labels:
      base: true
    values:
      - operator:
          replicas: 1
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
          metrics:
            enabled:
              - dns:query;ignoreAAAA
              - drop
              - tcp
              - flow
              - icmp
              - http
          tls:
            enabled: true
      - ipam:
          operator:
            clusterPoolIPv4PodCIDRList: 10.42.0.0/16
      - ipv4NativeRoutingCIDR: 10.42.0.0/16
      - ipv4:
          enabled: true
  - name: otel-backend
    namespace: otel-backend
    chart: ./charts/otel-backend
    labels:
      attack: true
  - name: opentelemetry-operator
    namespace: otel
    chart: open-telemetry/opentelemetry-operator
    version: 0.49.0
    labels:
      base: true
    values:
      - admissionWebhooks:
          certManager:
            enabled: false
            autoGenerateCert: true
  - name: hubble-collector
    namespace: kube-system
    chart: ./charts/hubble-collector
    labels:
      base: true
  - name: kafka
    namespace: anomaly-detection
    chart: bitnami/kafka
    version: 31.1.0
    labels:
      attack: true
    values:
      - kafka:
          replicas: 3
  - name: app-landscape
    namespace: app-landscape
    chart: ./charts/app-landscape
    labels:
      attack: true
  - name: dos-attack
    namespace: dos
    chart: ./charts/dos-attack
    labels:
      dos: true
  - name: port-scanner
    namespace: port-scanner
    chart: ./charts/port-scanner
    labels:
      scan: true
  - name: vuln-scanner
    namespace: owasp-zap
    chart: ./charts/owasp-zap
    labels:
      zap: true
    values:
      - zapcli:
          image:
            registry: https://hub.docker.com/r
            repository: zaproxy/zap-bare
            tag: 2.14.0
          debug:
            enabled: true
          spider:
            enabled: false
          recursive:
            enabled: false
          targetHost: http://10.42.1.107:3000/
