repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    values:
      - installCRDs: true
    labels:
      base: true
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.15.2
    labels:
      base: true
    values:
      - operator:
          replicas: 1
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
          metrics:
            enabled:
              - dns:query;ignoreAAAA
              - drop
              - tcp
              - flow
              - icmp
              - http
          tls:
            enabled: true
  - name: otel-backend
    namespace: otel-backend
    chart: ./charts/otel-backend
    labels:
      attack: true
  - name: opentelemetry-operator
    namespace: otel
    chart: open-telemetry/opentelemetry-operator
    version: 0.49.0
    labels:
      base: true
    values:
      - admissionWebhooks:
          certManager:
            enabled: false
            autoGenerateCert: true
  - name: hubble-collector
    namespace: kube-system
    chart: ./charts/hubble-collector
    labels:
      base: true
  - name: app-landscape
    namespace: app-landscape
    chart: ./charts/app-landscape
    labels:
      attack: true
  - name: dos-attack
    namespace: dos
    chart: ./charts/dos-attack
    labels:
      dos: true
  - name: port-scanner
    namespace: port-scanner
    chart: ./charts/portscanner
    labels:
      scan: true
