apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kube-owasp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kube-owasp.name" . }}
    helm.sh/chart: {{ include "kube-owasp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kube-owasp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: zap
        is_anomaly: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.zapcli.image.repository }}:{{ .Values.zapcli.image.tag }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.zapcli.image.pullPolicy }}
          args:
            - zap.sh
            - -quickurl
            - "{{ .Values.zapcli.targetHost }}"
            - -daemon
      restartPolicy: Never
