apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: otel-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: otel-backend
  template:
    metadata:
      labels:
        app: otel-backend
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - master
      containers:
      - name: otel-backend
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 1024Mi

